name: Context print

on: [push]

jobs:
  print-contexts:
    runs-on: ubuntu-lates
    steps:
      - name: print some github contexts
        run: echo "We are going to print some github contexts"

      - name: Dump job contexts
        env: 
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo $JOB_CONTEXT
      