name: Testing the container to build inside the step

on: [push]

jobs:
  container-inside-step:
    runs-on: ubuntu-latest
    steps:
      - name: Installing the node
        uses: docker://solr:8.6
        with:
          entrypoint: '/opt/solr/bin/solr' 
          args: 'status'