name: Using containers in Guthub Actions

on: [push]

jobs:
  solr-docker:
    runs-on: ubuntu-latest
    container: # any steps further will run inside the container
      image: solr:latest
      options: --user root
    steps:
      - name: make solr data Directory
        run: |
          mkdir -p /var/solr/data  
          mkdir -p /var/solr/logs
      - name: check solr status
        run: |
          /opt/solr/bin/solr status
        continue-on-error: true
      - name: start solr server
        if: always()
        run: |
          /opt/solr/bin/solr start -force
          sleep 30
          sudo find /var -type f -name solr.log
          sudo find /opt -type f -name solr.log
          echo `locate solr.log`
      - name: check solr status again
        run: |
          /opt/solr/bin/solr status
      - name: check solr cores status
        run: |
          curl -v 'http://localhost:8983/solr/admin/cores?action=STATUS'
      - name: Tail solr logs
        run: |
          tail -n 200 /var/solr/server/logs/solr.log
          
         