name: Using containers in Guthub Actions

on: [push]

jobs:
  solr-docker:
    runs-on: ubuntu-latest
    container: 
      image: solr:latest
    steps:
      - name: make solr data Directory
        run: |
          mkdir -p /var/solr/data  
      - name: check solr status
        run: |
          /opt/solr/bin/solr status
        continue-on-error: true
      - name: start solr server
        if: always()
        run: |
          /opt/solr/bin/solr start
          sleep 30
      - name: check solr status again
        run: |
          /opt/solr/bin/solr status
      - name: check solr cores status
        run: |
          curl -v 'http://localhost:8983/solr/admin/cores?action=STATUS'
      - name: Tail solr logs
        run: |
          tail -n 200 /var/solr/logs/solr.log
          
         