name : Designing the strategy

on: push

env:
  NODE_VER: ${{ secrets.NODE_VER }}

jobs:
  node-install:
    runs-on: ubuntu-latest
    steps:
      - name: Check default node version
        run: | 
          node -v
          echo $NODE_VER
      - name: Doing matrix wise node version node-install
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6