name: Test revision

on: [push]

jobs:
  test-revison:
    runs-on: ubuntu-latest
    steps:
      - name: testing the checkout
        uses: actions/checkout@v3
      
      - name: Printing the directory files, if any
        run:  |
          git --version
          ls
          cd $GITHUB_WORKSPACE
          pwd
          git checkout $GITHUB_SHA
